# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: 753cindy@naver.com
brand: JungHakyoung
headline: Frontend, PHP Developer
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jjung45.github.io/wjdgkrud_blog.github.io/" # the base hostname & protocol for your site
copyright: 2018 wjdgkrud. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: 753cindy@naver.com
phone: 010-7271-8863

# Tracking
googleAnalitycsID: UA-83933844-1

